src/APS.Presentation.Web/Controllers/AgendamentosController.cs
using APS.Application.Interfaces;
using APS.Application.ViewModel.Agendamentos;
using APS.Presentation.Web.Controllers.Common;
using APS.Presentation.Web.Helpers.Attributes;
using System;
using System.Web.Mvc;

namespace APS.Presentation.Web.Controllers
{
    public class AgendamentosController : BaseController
    {
        private readonly IAgendamentoAppService agendamentoAppService;
        private readonly IClienteAppService clienteAppService;

        public AgendamentosController(IAgendamentoAppService agendamentoAppService, IClienteAppService clienteAppService)
        {
            this.agendamentoAppService = agendamentoAppService;
            this.clienteAppService = clienteAppService;
        }

        public ActionResult Index()
        {
            return View(agendamentoAppService.BuscarTodos());
        }

        public ActionResult Cadastrar()
        {
            CarregarCombos();
            return View(new CadastroViewModel { });
        }

        public ActionResult Atualizar(long id)
        {
            CarregarCombos();
            var viewModel = agendamentoAppService.BuscarPorId(id);
            return View("Cadastrar", viewModel);
        }

        [HttpPost]
        public ActionResult Cadastrar(CadastroViewModel cadastroViewModel)
        {
            agendamentoAppService.Cadastrar(cadastroViewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Atualizar(CadastroViewModel cadastroViewModel)
        {
            agendamentoAppService.Atualizar(cadastroViewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Excluir(long id)
        {
            agendamentoAppService.Remover(id);
            return new HttpStatusCodeResult(200);
        }

        private void CarregarCombos()
        {
            ViewBag.Clientes = clienteAppService.BuscarTodos(true);
        }
    }
}

src/APS.Presentation.Web/Controllers/CalendarioController.cs
using APS.Application.Interfaces;
using APS.Presentation.Web.Controllers.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APS.Presentation.Web.Controllers
{
    public class CalendarioController : BaseController
    {
        private readonly IAgendamentoAppService agendamentoAppService;

        public CalendarioController(IAgendamentoAppService agendamentoAppService)
        {
            this.agendamentoAppService = agendamentoAppService;
        }

        public ActionResult Index()
        {
            var lista = agendamentoAppService.BuscarPorDataMes(DateTime.Now);
            return View(lista);
        }

        [HttpGet]
        public JsonResult BuscarPorDataMes(DateTime data)
        {
            var lista = agendamentoAppService.BuscarPorDataMes(data);
            return Json(lista,JsonRequestBehavior.AllowGet);
        }
    }
}

src/APS.Presentation.Web/Controllers/ClientesController.cs
using APS.Application.Interfaces;
using APS.Application.ViewModel.Clientes;
using APS.Presentation.Web.Controllers.Common;
using APS.Presentation.Web.Helpers.Attributes;
using System.Web.Mvc;

namespace APS.Presentation.Web.Controllers
{
    public class ClientesController : BaseController
    {        

        private readonly IClienteAppService clienteAppService;

        public ClientesController(IClienteAppService clienteAppService)
        {
            this.clienteAppService = clienteAppService;
        }

        public ActionResult Index()
        {
            return View(clienteAppService.BuscarTodos());
        }

        public ActionResult Cadastrar()
        {
            return View(new CadastroViewModel { Ativo=true});
        }

        public ActionResult Atualizar(long id)
        {
            var viewModel = clienteAppService.BuscarPorId(id);
            return View("Cadastrar", viewModel);
        }

        [HttpPost]
        public ActionResult Cadastrar(CadastroViewModel cadastroViewModel)
        {
            clienteAppService.Cadastrar(cadastroViewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Atualizar(CadastroViewModel cadastroViewModel)
        {
            clienteAppService.Atualizar(cadastroViewModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Excluir(long id)
        {
            clienteAppService.Remover(id);
            return new HttpStatusCodeResult(200);
        }

        [HttpGet]
        public JsonResult BurcarCliente(long id)
        {
            var cliente = clienteAppService.BuscarPorId(id);
            return Json(cliente, JsonRequestBehavior.AllowGet);
        }
    }
}

src/APS.Presentation.Web/Views/Shared/Layout/_Navbar.cshtml
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
            <figure class="nav-logo">
                <img src="@Url.Content("~/Content/midia/logo.png")" class="logo">
            </figure>
            <span>ACF</span>
        </a>
    </div>
    @if (AplicacaoWeb.UsuarioLogado.EstaLogado)
    {
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="@Url.Action("LogOff", "Home")"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                    </li>
                </ul>
            </li>
        </ul>
    }
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="@Url.Action("Index", "Clientes")"><i class="fa fa-user-circle fa-fw"></i> Clientes</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Agendamentos")"><i class="fa fa-calendar-plus-o fa-fw"></i> Agendamento</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Calendario")"><i class="fa fa-table fa-fw"></i> Calendario</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-files-o fa-fw"></i> Consultas<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#">Em Desenvolvimento....</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>